export const mockCabs = [
  {
    name: 'Bajaj Auto Rickshaw',
    type: 'Auto',
    price: 12,
    images: [
      'https://images.unsplash.com/photo-1511918984145-48de785d4c4e?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=facearea&w=400&q=80',
    ],
    features: ['3 Passengers', 'Economical'],
    rating: 4.2,
    description: 'Affordable Bajaj Auto Rickshaw perfect for short city trips and local transportation. Ideal for small groups and budget-conscious travelers.',
    specifications: ['Engine: 150cc', 'Mileage: 35 km/l', 'Seating: 3 Passengers', 'Luggage: 1 Bag', 'AC: No', 'Music System: No'],
    amenities: ['Economical', 'Easy Navigation', 'Local Knowledge', 'Quick Service'],
    policies: ['Free Cancellation: 1 hour before', 'Waiting Time: 10 minutes free', 'Extra Km: ₹8/km', 'Night Charges: 5% extra'],
  },
  {
    name: 'Swift Dzire (AC)',
    type: 'Sedan',
    price: 22,
    images: [
      'https://images.unsplash.com/photo-1511918984145-48de785d4c4e?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=facearea&w=400&q=80',
    ],
    features: ['AC', '4 Passengers'],
    rating: 4.6,
    description: 'Comfortable and reliable Swift Dzire sedan perfect for city travel and airport transfers. Spacious interior with modern amenities.',
    specifications: ['Engine: 1.2L Petrol', 'Mileage: 22 km/l', 'Seating: 4 Passengers', 'Luggage: 2 Bags', 'AC: Yes', 'Music System: Yes'],
    amenities: ['Air Conditioning', 'Music System', 'GPS Navigation', 'Child Seat Available', 'WiFi Hotspot', 'Phone Charger'],
    policies: ['Free Cancellation: 2 hours before', 'Waiting Time: 15 minutes free', 'Extra Km: ₹12/km', 'Night Charges: 10% extra'],
  },
  {
    name: 'Maruti Ertiga (AC)',
    type: 'SUV',
    price: 28,
    images: [
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1511918984145-48de785d4c4e?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=facearea&w=400&q=80',
    ],
    features: ['AC', '6 Passengers'],
    rating: 4.7,
    description: 'Spacious Maruti Ertiga SUV perfect for family trips and group travel. Comfortable seating with modern amenities.',
    specifications: ['Engine: 1.5L Petrol', 'Mileage: 20 km/l', 'Seating: 6 Passengers', 'Luggage: 4 Bags', 'AC: Yes', 'Music System: Yes'],
    amenities: ['Air Conditioning', 'Music System', 'GPS Navigation', 'Child Seat Available', 'WiFi Hotspot', 'Phone Charger', 'Spacious Interior'],
    policies: ['Free Cancellation: 3 hours before', 'Waiting Time: 20 minutes free', 'Extra Km: ₹18/km', 'Night Charges: 15% extra'],
  },
  {
    name: 'Force Traveler 11',
    type: 'Traveler',
    price: 60,
    images: [
      'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=facearea&w=400&q=80',
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=facearea&w=400&q=80',
    ],
    features: ['AC', '11 Passengers'],
    rating: 4.4,
    description: 'Spacious Force Traveler ideal for large groups, corporate events, and family gatherings. Comfortable seating for up to 11 passengers.',
    specifications: ['Engine: 2.5L Diesel', 'Mileage: 15 km/l', 'Seating: 11 Passengers', 'Luggage: 8 Bags', 'AC: Yes', 'Music System: Yes'],
    amenities: ['Air Conditioning', 'Music System', 'GPS Navigation', 'Child Seat Available', 'WiFi Hotspot', 'Phone Charger', 'Spacious Interior'],
    policies: ['Free Cancellation: 4 hours before', 'Waiting Time: 30 minutes free', 'Extra Km: ₹25/km', 'Night Charges: 20% extra'],
  },
];

export const cardStyle = {
  background: '#fff',
  borderRadius: '1.5rem',
  boxShadow: '0 2px 16px rgba(122,107,87,0.13)',
  overflow: 'hidden',
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'stretch',
  minHeight: 340,
  position: 'relative',
  transition: 'transform 0.25s cubic-bezier(.4,2,.6,1), box-shadow 0.25s',
  cursor: 'pointer',
  animation: 'fadeInCabCard 0.7s cubic-bezier(.4,2,.6,1)',
} as React.CSSProperties; 